window:
  dimensions:
    columns: 125
    lines: 40
  title: Terminal

font:
  normal:
    family: IBM Plex Mono
    style: Regular
  bold:
    family: IBM Plex Mono
    style: Bold
  italic:
    family: IBM Plex Mono
    style: Italic
  bold_italic:
    family: IBM Plex Mono
    style: Bold Italic

  size: 14.0

# Colors (Icelandic Theme)
colors:
  primary:
    background: '#3b4252'
    foreground: '#d8dee9'

  normal:
    black:   '#2e3440'
    red:     '#cc6666'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#d8dee9'

